CREATE TABLE IF NOT EXISTS ai_bot_media_ksi_performance (
    record_key CHAR(64) NOT NULL,
    period_month DATE NOT NULL,
    year SMALLINT NOT NULL,
    month TINYINT UNSIGNED NOT NULL,
    platform VARCHAR(100) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    tier VARCHAR(50) NOT NULL,
    big_v_cost DECIMAL(20,6) NOT NULL,
    bet DECIMAL(20,8) NULL,
    nickname VARCHAR(255) NULL,
    kol_id_front VARCHAR(255) NULL,
    redirect_platform VARCHAR(100) NULL,
    content_format VARCHAR(100) NULL,
    published_at DATETIME NOT NULL,
    source_month TINYINT UNSIGNED NULL,
    follower_count BIGINT NULL,
    view_count BIGINT NULL,
    comment_count BIGINT NULL,
    like_count BIGINT NULL,
    repost_count BIGINT NULL,
    collect_count BIGINT NULL,
    ttl_engagement BIGINT NULL,
    big_category VARCHAR(255) NULL,
    sub_category VARCHAR(255) NULL,
    sku TEXT NULL,
    kol_id_back VARCHAR(255) NULL,
    content_id VARCHAR(255) NULL,
    title TEXT NULL,
    kol_type VARCHAR(100) NOT NULL,
    selectivity VARCHAR(100) NULL,
    tier_secondary VARCHAR(50) NULL,
    source_file VARCHAR(255) NOT NULL,
    source_sheet VARCHAR(100) NOT NULL,
    source_row_number INT UNSIGNED NOT NULL,
    import_batch_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (record_key),
    INDEX idx_ksi_period_brand (period_month, brand),
    INDEX idx_ksi_brand_period (brand, period_month),
    INDEX idx_ksi_tier_period (tier, period_month),
    INDEX idx_ksi_type_period (kol_type, period_month),
    INDEX idx_ksi_platform_period (platform, period_month),
    INDEX idx_ksi_kol_period (kol_id_front, period_month),
    INDEX idx_ksi_nickname_period (nickname, period_month),
    INDEX idx_ksi_content_id (content_id),
    CONSTRAINT chk_ksi_month CHECK (month BETWEEN 1 AND 12),
    CONSTRAINT chk_ksi_source_month CHECK (
        source_month IS NULL OR source_month BETWEEN 1 AND 12
    )
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
